version: '{branch}-{build}'
image: Visual Studio 2017

branches:
  except:
    - ubuntu-build

environment:
  matrix:
  # MSVC x64
  - name: x64
    platform: x64
    qt: 5.12\msvc2017_64
    openssl: C:\OpenSSL-Win64
    
  # MSVC x86
  - name: x86
    platform: x86
    qt: 5.12\msvc2017
    openssl: C:\OpenSSL-Win32

init:
  - set PATH=C:\Qt\%qt%\bin;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %platform%

configuration:
  - Release

before_build:
  - git submodule update --init --recursive

build_script:
  - qmake GM-Companion.pro
  - nmake
  - nmake check

after_build:
  - windeployqt.exe --release --qmldir C:\Qt\%qt%\qml release\gm-companion.exe
  - cmd: copy /y "%openssl%\bin\*eay32.dll" release\out

artifacts:
  - path: release\
    name: gm-companion-%platform%
    type: zip
