version: '{branch}-{build}'

branches:
  except:
    - ubuntu-build

image: Visual Studio 2017

environment:
  matrix:
  # MinGW x64
  - name: win64
    platform: mingw
    qt: 5.12\mingw73_64
    suffix: mingw
    
  # MSVC x64
  - name: win64
    platform: amd64
    qt: 5.12\msvc2017_64
    suffix: msvc2017
    
  # MSVC x86
  - name: win32
    platform: amd64_x86
    qt: 5.12\msvc2017
    suffix: msvc2017

init:
  - set PATH=C:\Qt\%qt%\bin;%PATH%
  - if %platform%==mingw set PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\bin;%PATH%
  - if not %platform%==mingw call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %platform%

configuration:
  - Release

install:

before_build:
  - git submodule update --init --recursive
  - qmake GM-Companion.pro

build_script:
  - if not %platform%==mingw (nmake) else (mingw32-make)
  - if not %platform%==mingw (nmake check)

after_build:
  - windeployqt.exe --release --no-compiler-runtime --qmldir C:\Qt\%qt%\qml release\out\gm-companion.exe
  - cmd: copy /y "C:\OpenSSL-Win64\bin\*eay32.dll" release\out

artifacts:
  - path: release\out
    name: gm-companion-%platform%
    type: zip
