version: '{branch}-{build}'
image: Visual Studio 2015

branches:
  except:
    - ubuntu-build

environment:
  matrix:  
  # MinGW x86_64  
  - COMPILER_NAME: mingw-64
    PLATFORM_ARCH: x86_64
    QT_PATH: C:\Qt\5.13\mingw73_64
    QT_TOOLS: C:\Qt\Tools
    MINGW_PATH: C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64
    OPENSSL: C:\OpenSSL-Win64
    BUILD_SCRIPT: build-mingw.bat
    
  # MinGW x86  
#  - COMPILER_NAME: mingw-32
#    PLATFORM_ARCH: x86
#    QT_PATH: C:\Qt\5.12\mingw73_32
#    MINGW_PATH: C:\Qt\Tools\mingw730_32
#    OPENSSL: C:\OpenSSL-Win32
#    BUILD_SCRIPT: build-mingw.bat

init:
  - cmd: set PATH=%MINGW_PATH%\bin;%PATH%
  - cmd: set PATH=%QT_PATH%\bin;%PATH%

configuration:
  - Release

before_build:
  - git submodule update --init --recursive
  - cmd: cd deploy\appveyor
  - cmd: call download-libs.bat

build_script:
  - cmd: cd deploy\appveyor
  - cmd: call %BUILD_SCRIPT%

after_build:
  - cmd: cd deploy
  - cmd: call deploy-win.bat

artifacts:
  - path: release\deploy
    name: gm-companion-%COMPILER_NAME%
    type: zip
    
  - path: deploy\installer\repository
    name: gm-companion-repository-%COMPILER_NAME%
    type: zip
    
  - path: deploy\installer\gm-companion-installer-x64.exe
    name: gm-companion-installer-x64.exe
    
  - path: deploy\installer\gm-companion-online-installer-x64.exe
    name: gm-companion-online-installer-x64.exe

on_failure:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
