version: '{branch}-{build}'

platform:
  - x64

configuration:
  - Release

install:
  - set QTDIR=C:\Qt\5.11\mingw53_32
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin
  - cmd: git submodule update --init --recursive
  
build_script:
  - cmd: qmake GM-Companion.pro
  - mingw32-make
  
artifacts:
  - path: '**\*.exe'
    name: gm-companion
