version: '{branch}-{build}'

branches:
  except:
    - ubuntu-build

image: Visual Studio 2017

platform: x64

configuration:
  - Release

install:
  - set QTDIR=C:\Qt\5.11\msvc2017_64
  - set PATH=%QTDIR%\bin;%PATH%

before_build:
  - git submodule update --init --recursive
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%
  - qmake GM-Companion.pro

build_script:
  - nmake
  - nmake check

after_build:
  - windeployqt.exe --release --qmldir %QTDIR%\qml release\out\gm-companion.exe

artifacts:
  - path: release\out
    name: gm-companion-win64
    type: zip
