notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

image: Visual Studio 2015

environment:
  matrix:
  - CMAKE_GENERATOR: "Visual Studio 14 2015"
    QT5: C:\Qt\5.8\msvc2015
  - CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
    QT5: C:\Qt\5.8\msvc2015_64

before_build:
- set Path=%QT5%\bin;%Path%
- cmake -H. -Bbuild -G "%CMAKE_GENERATOR%" -DCMAKE_SYSTEM_VERSION=10.0 "-DCMAKE_PREFIX_PATH=%QT5%" -DENABLE_GUI=ON

build_script:
- cmake --build build --config "%CONFIGURATION%" -- %MSBUILD_FLAGS%

after_build:
- cmake --build build --config "%CONFIGURATION%" --target check -- %MSBUILD_FLAGS%
- cmake --build build --config "%CONFIGURATION%" --target package -- %MSBUILD_FLAGS%
