notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

environment:
    matrix:
    - PLATFORM: x86
      QT5: C:\Qt\5.9.1\msvc2015
    - PLATFORM: x86_amd64
      QT5: C:\Qt\5.9.1\msvc2015_64

install:
    - call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %PLATFORM%

before_build:
    - set Path=%QT5%\bin;%Path%
    - mkdir build

build_script:
    - cmake -G "NMake Makefiles" -H. -Bbuild -DCMAKE_PREFIX_PATH=%QT5%
    - cmake --build build
