sonar.projectKey=PhilInTheGaps_GM-Companion
sonar.organization=rophil
sonar.projectName=gm-companion
sonar.host.url=https://sonarcloud.io

sonar.sources=src,app
sonar.tests=tests

sonar.cfamily.compile-commands=build/bw-output/compile_commands.json
sonar.cfamily.gcov.reportsPath=build/
sonar.cfamily.cache.enabled=true
sonar.cfamily.cache.path=sonar-cache/